import { parseProjectCommand } from '../src/aiExpert/parseProjectCommand';
import { getMarketFundingSnapshot } from '../src/data/bankMarketRates';
import { detectExpertIntent,composeExpertAnswer } from '../src/aiExpert/composeExpertAnswer';
import { evaluatePrograms } from '../src/logic/decisionEngine';
import { buildExpertContext } from '../src/aiExpert/buildExpertContext';
import type { UserQuery } from '../src/types/damu';
const failures:string[]=[];
function check(name:string,ok:boolean,info=''){console.log((ok?'EDGE_PASS':'EDGE_FAIL')+' '+name+' '+info);if(!ok)failures.push(name)}
const change=(s:string)=>parseProjectCommand(s);
const base:UserQuery={oked_code:'45.2',region_id:'astana-city',region_name:'Астана',location_name:'Астана',location_level:'city',location_role:'project',district_name:'',settlement_type:'',settlement_type_confirmed:false,entity_type:'ТОО',business_status:'действующий',operating_years:3,purpose:'Инвестиции',amount_kzt:150000000,instrument_preference:'Гарантирование',tax_arrears:false,overdue_debt_days:0,social_enterprise_registry:false};
const ctx=buildExpertContext(evaluatePrograms(base));
const conflicting=change('Измени сумму на 100 млн, нет, на 200 млн');
check('Conflicting amounts must block change',conflicting.unresolved.length>0,JSON.stringify(conflicting));
const region=change('Перенеси проект из Алматы в Астану');
check('Origin city cannot override target city',region.changes.some(x=>x.field==='region_id'&&x.value==='astana-city'),JSON.stringify(region));
const missing=change('Поменяй ОКЭД на 45.2 и сумму финансирования');
check('Unresolved amount blocks partial apply',missing.unresolved.length>0,JSON.stringify(missing));
const noAmount=change('Измени сумму на 40');
check('Unqualified 40 cannot be 40 tenge',!noAmount.changes.some(x=>x.field==='amount_kzt'),JSON.stringify(noAmount));
const guaranteeQuestion='Почему Гарантийный фонд 1 не подходит?';
check('Guarantee exclusion question remains guarantee response',detectExpertIntent(guaranteeQuestion)==='guarantee_routes');
const banks=getMarketFundingSnapshot(base);
check('Bank alternatives have checked-on dates',banks.products.every(x=>/^\d{4}-\d{2}-\d{2}$/.test(x.checkedOn)));
const now=new Date('2026-10-09T00:00:00Z').getTime();
const stale=banks.products.filter(x=>now-Date.parse(x.checkedOn+'T00:00:00Z')>30*86400000);
check('Stale source reporting explicit',stale.length===0 || composeExpertAnswer(ctx,'Какие банковские альтернативы?').body.some(x=>/устарел|требуется перепровер/.test(x)));
const why=composeExpertAnswer(ctx,'Почему не подходит Гарантийный фонд 1?');
check('No categorical approval in guarantee answer',!why.body.some(x=>/гарантия одобрена|кредит одобрен/i.test(x)));
console.log('EDGE_SUMMARY '+JSON.stringify({total:8,failed:failures.length,failures}));if(failures.length)process.exitCode=1;
