import {evaluatePrograms} from '../src/logic/decisionEngine';
import {buildExpertContext} from '../src/aiExpert/buildExpertContext';
import {composeExpertAnswer} from '../src/aiExpert/composeExpertAnswer';
import type {UserQuery} from '../src/types/damu';
const q:UserQuery={oked_code:'45.2',region_id:'astana-city',region_name:'Астана',location_name:'Астана',location_level:'city',location_role:'project',district_name:'',settlement_type:'',settlement_type_confirmed:false,entity_type:null,business_status:'действующий',operating_years:3,purpose:'Инвестиции',amount_kzt:150000000,instrument_preference:'Гарантирование',tax_arrears:false,overdue_debt_days:0,social_enterprise_registry:false};
const ctx=buildExpertContext(evaluatePrograms(q),'2026-10-09T00:00:00Z');
const check=(name:string,pass:boolean)=>{console.log((pass?'ENTITY_PASS ':'ENTITY_FAIL ')+name);if(!pass)process.exitCode=1;};
const prompt='Какие банки подходят действующему ТОО по ОКЭД 45.2 в Астане для инвестиций 150 млн тенге?';
const a=composeExpertAnswer(ctx,prompt);
check('recognizes TOO in question',a.body.some(x=>x.includes('форма бизнеса ТОО (со слов заявителя)')));
check('explicitly identifies unconfirmed form',a.body.some(x=>x.includes('ТОО указано в вопросе, но не подтверждено в анкете')));
check('does not ask to re-enter already mentioned form',!a.body.find(x=>x.startsWith('Ещё необходимо уточнить'))?.includes('форму бизнеса'));
check('never mutates questionnaire',ctx.project.entityType==null&&q.entity_type==null);
check('preserves sources',a.sourceIds.length>1);
const conflict=composeExpertAnswer(buildExpertContext(evaluatePrograms({...q,entity_type:'ИП'})) ,prompt);
check('conflict flagged',conflict.body.some(x=>x.includes('В анкете указано «ИП», а в вопросе — «ТОО»')));
const ambiguity=composeExpertAnswer(ctx,'Какие банки рассматривают ТОО или ИП?');
check('ambiguity flagged',ambiguity.body.some(x=>x.includes('одновременно упомянуты ТОО и ИП')));
const noMention=composeExpertAnswer(ctx,'Какие банковские альтернативы?');
check('unspecified form remains missing',noMention.body.some(x=>x.startsWith('Ещё необходимо уточнить')&&x.includes('форму бизнеса')));
console.log('ENTITY_SUMMARY 8 checks');
