import {evaluatePrograms} from '../src/logic/decisionEngine';
import {buildExpertContext} from '../src/aiExpert/buildExpertContext';
import {composeExpertAnswer} from '../src/aiExpert/composeExpertAnswer';
import {getMarketFundingSnapshot} from '../src/data/bankMarketRates';
import type {UserQuery} from '../src/types/damu';
const q:UserQuery={oked_code:'45.2',region_id:'astana-city',region_name:'Астана',location_name:'Астана',location_level:'city',location_role:'project',district_name:'',settlement_type:'',settlement_type_confirmed:false,entity_type:'ТОО',business_status:'действующий',operating_years:3,purpose:'Инвестиции',amount_kzt:150000000,instrument_preference:'Гарантирование',tax_arrears:false,overdue_debt_days:0,social_enterprise_registry:false};
const c=buildExpertContext(evaluatePrograms(q),'2026-10-09T00:00:00Z');
const fails:string[]=[];function ck(name:string,yes:boolean){console.log((yes?'UAT_PASS ':'UAT_FAIL ')+name);if(!yes)fails.push(name);}
const prompt='Могу ли я получить гарантию по Гарантийному фонду 1 «Даму» на кредит 150 млн тенге для автосервиса в Астане?';
const answer=composeExpertAnswer(c,prompt);
ck('focused GF1',answer.title.includes('Гарантийный фонд 1'));
ck('GF1 85%',answer.body.some(x=>x.includes('85%')));
ck('GF1 127.5m',answer.body.some(x=>x.includes('127 500 000')||x.includes('127 500 000')));
ck('GF1 commission',answer.body.some(x=>x.includes('1,5%')));
ck('GF1 status preserved',answer.body.some(x=>x.includes(c.decisions.find(x=>x.programId==='damu.guarantee.guarantee_fund_1')?.decisionLabel||'unlikely')));
ck('GF1 links',answer.sourceIds.includes('SRC-GF1'));
ck('GF1 excludes social noise',!answer.body.some(x=>x.includes('Поддержка субъектов индустриально')));
const b=composeExpertAnswer(c,'Какие коммерческие банки могут дать 150 млн тенге для инвестиционного проекта?');
ck('bank intent',b.intent==='market_funding');
ck('known project 150m',b.body.some(x=>x.includes('150 000 000')||x.includes('150 000 000')));
ck('known TOO',b.body.some(x=>x.includes('форма бизнеса ТОО')));
ck('no repeat known amount in missing',!b.body.find(x=>x.startsWith('Ещё необходимо'))?.includes('сумму кредита'));
ck('no 30-day investment limit',!b.body.some(x=>x.includes('Кредитный лимит на счёт')));
ck('investment products',b.body.some(x=>x.includes('Business Medium')));
ck('source links retained',b.sourceIds.some(x=>x.includes('HALYK')));
ck('bank underwriting',b.body.some(x=>x.includes('кредитную историю')));
const w=buildExpertContext(evaluatePrograms({...q,purpose:'Оборотные средства'}),'2026-10-09T00:00:00Z');
ck('working capital keeps short limit',getMarketFundingSnapshot({...q,purpose:'Оборотные средства'}).products.some(x=>x.sourceId.includes('BCC-CREDIT-LIMIT')));
ck('IP-only excludes TOO',!getMarketFundingSnapshot(q).products.some(x=>x.sourceId.includes('HALYK-ONLINE-IP')||x.sourceId.includes('BEREKE-IP')));
ck('working capital bank answer',composeExpertAnswer(w,'Какие банковские альтернативы?').body.some(x=>x.includes('Кредитный лимит на счёт')));
console.log('UAT_BUNDLE_SUMMARY '+JSON.stringify({total:18,passed:18-fails.length,failed:fails}));if(fails.length)process.exitCode=1;